test pull-request olya
AndrewPechnikov/Command-React-App pull request #1
Opened 2023-05-17 19:34 UTC by olha-vrnn

Translate the file README.md into Ukrainian.

2023-05-18 14:14 UTC, AndrewPechnikov requested changes

2023-05-18 14:14 UTC, AndrewPechnikov commented on README.md
> +   скрипт буде вказано в чому проблема.
Дякую за переклад. Для розуміння процесу виправлення помилки, додай одну пусту, або строчку зі смайликом в кінці. Коли зробиш, постав палець вгору на смайлику коментаря.

2023-05-19 05:53 UTC, AndrewPechnikov approved these changes

2023-05-19 05:58 UTC, AndrewPechnikov submitted a review, later dismissed

2023-05-19 12:56 UTC, hrybach-oleksiy reviewed
looks good

2023-05-20 17:56 UTC, hrybach-oleksiy submitted a review, later dismissed

2023-05-21 06:12 UTC, AndrewPechnikov approved these changes

2023-05-21 06:12 UTC, merged