Feature/RA1_hero-card
AndrewPechnikov/Command-React-App pull request #12
Opened 2023-05-25 13:10 UTC by hrybach-oleksiy

2023-05-26 10:36 UTC, AndrewPechnikov requested changes

2023-05-26 10:36 UTC, AndrewPechnikov commented on src/components/RA-1/RA1.jsx
> +    const backgrounds = {
Дивись, через бекграунд контентні зображення наче не додаються, додаються тільки декоративні. В даному випадку, це контентне зображення. Ось вирізки з конспекту на який я посилаюсь. 
'''Контентні зображення - несуть смислове навантаження, належать до змісту сторінки і допомагають донести до користувача корисну для нього інформацію. Вони додаються в HTML-розмітці за допомогою тегу <img> з обов'язково заповненим атрибутом alt, що описує зображення.

Фотографія продукту на картці товару в інтернет-магазині, фотографії членів команди, логотип компанії, рекламні банери, карти з локацією, зображення слайдера, аватарки - це все контентні зображення.

Декоративні зображення - використовуються виключно для додаткового оформлення. Вони не несуть жодної корисної інформації і слугують виключно для «краси». Додаються через CSS як фон, використовуючи властивість background-image, або розмічаються в HTML тегом <svg> (у разі векторної графіки).

Кастомні маркери списків, усілякі допоміжні іконки, плашки, фонові зображення блоків - це все декоративні зображення.'''

2023-05-26 10:36 UTC, AndrewPechnikov commented on src/components/RA-1/index.jsx
> +
Ти міг код писати прямо тут. Чому створив ще один jsx?

2023-05-26 13:22 UTC, hrybach-oleksiy commented on src/components/RA-1/index.jsx
> +
Трохи збило з пантелику, чому файл компоненту називається не так як компонент. І десь бачив ще такий підхід. що в папці з компонентом є індекс і інші файли пов'язані саме з компонентом, потім усе це зкидується в індекс. Тому подумав, шо може це саме воно. Не зрозуміло навіщо тоді індекс взагалі тут

2023-05-26 13:25 UTC, hrybach-oleksiy commented on src/components/RA-1/RA1.jsx
> +    const backgrounds = {
є сенс. перероблю

2023-05-26 19:56 UTC, AndrewPechnikov commented on src/components/RA-1/index.jsx
> +
Індекс я використовую, тому що достатньо прописати шлях до папки, а індекс підхватується сам. Мене так друг програміст навчив, наскільки це правильно, дискутивне питання.

2023-05-26 20:40 UTC, hrybach-oleksiy commented on src/components/RA-1/index.jsx
> +
Так шо переробити в індексі все, чи як?

2023-05-27 12:24 UTC, AndrewPechnikov commented on src/components/RA-1/index.jsx
> +
Не треба, хай буде так. У Олі так само, це не приципово.

2023-05-27 12:24 UTC, AndrewPechnikov approved these changes

2023-05-27 13:06 UTC, olha-vrnn approved these changes

2023-05-28 17:52 UTC, DenisNexus approved these changes

2023-05-28 18:37 UTC, merged