init: add test component
AndrewPechnikov/Command-React-App pull request #2
Opened 2023-05-17 20:10 UTC by hrybach-oleksiy

just a test pull request

2023-05-18 14:13 UTC, AndrewPechnikov requested changes

2023-05-18 14:13 UTC, AndrewPechnikov commented on src/components/App.jsx
> +      <TestComponent />
Видали будь ласка цю строку, бо це піде в main. Коли зробиш, постав палець вгору на смайлику коментаря.

2023-05-18 14:13 UTC, AndrewPechnikov commented on src/components/TestComponent.jsx
> +const TestComponent = () => {
Цей файл теж видали. Коли зробите, постав палець вгору на смайлику коментаря.

2023-05-19 05:29 UTC, olha-vrnn approved these changes

2023-05-19 05:52 UTC, AndrewPechnikov approved these changes

2023-05-19 13:14 UTC, merged